image: gitlab-registry.cern.ch/mramospe/mpt/ubuntu-20.04:gcc10

stages:
- build
- test

build:
  stage: build
  script:
  - mkdir build
  - cd build
  - cmake ../ -DINSTALL_TESTS=ON -DCMAKE_CXX_COMPILER=$(which g++-10)
  - make install
  artifacts:
     paths:
     - build/

test:
  stage: test
  script:
  - ./build/test/cpp/test_all
  - ./build/test/cpp/test_keywords
  - ./build/test/cpp/test_members
  - ./build/test/cpp/test_signature
  - ./build/test/cpp/test_smart_enum
  - ./build/test/cpp/test_types
  - ./build/test/cpp/test_values
  dependencies:
  - build

cmake:
  stage: test
  script:
  - mkdir test/cmake/build
  - cd test/cmake/build
  - cmake ../ -DCMAKE_INSTALL_PREFIX=../../../build/cmake -DCMAKE_CXX_COMPILER=$(which g++-10)
  - make
  - ./main
  dependencies:
  - build

format:
  stage: test
  script:
  - clang-format-10 $(find ./ -regex "\./\(include\|test\).*\(hpp\|cpp\)" -type f) --dry-run --Werror
