dist: focal
language: cpp
compiler: gcc

os: linux
addons:
  apt:
    packages:
    - g++-10
    - cmake
    - clang-format
env:
- CC=gcc-10 CXX=g++-10

branches:
  only:
  - master
  - devel

before_install:
- ${CC} --version
- ${CXX} --version
- cmake --version
- clang-format --version

install:
- mkdir build
- cd build
- cmake ../ -DINSTALL_TESTS=ON -DCMAKE_CXX_COMPILER=${CXX}
- make install
- cd ..

jobs:
  include:
  - name: cpp
    script:
    - ./build/test/cpp/test_all
    - ./build/test/cpp/test_keywords
    - ./build/test/cpp/test_members
    - ./build/test/cpp/test_signature
    - ./build/test/cpp/test_smart_enum
    - ./build/test/cpp/test_types
    - ./build/test/cpp/test_values
  - name: cmake
    script:
    - mkdir test/cmake/build
    - cd test/cmake/build
    - cmake ../ -DCMAKE_INSTALL_PREFIX=../../../build/cmake
    - make
    - ./main
  - name: format
    install: " "
    script:
    - clang-format $(find ./ -regex "\./\(include\|test\).*\(hpp\|cpp\)" -type f) --dry-run --Werror
