version: 2.1

jobs:
  success-ward:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Run a simple command
          command: echo success

workflows:
  gh-pages:
    jobs:
      - success-ward
